### PR TITLE
Updated README and Added Licenses

### LINKED ISSUE #10: Update readme dependencies

### PR DESCRIPTION
**Pull request by parseccentric**
# Updated README and Added Licenses

**Updated Readme**

* Added `config.js` instructions
* Updated dependencies (Fixes #10) and separated into Production vs Development
* Added note about chat namespace being experimental

**Added Licenses**

* Added licenses to all files except HTML files
* Did not add licenses to legacy `tests` folder's files, because we'll deprecate `tests` soon

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Testing 
- [ ] Change that requires a documentation update
- [x] Documentation change

# How Has This Been Tested?

Do `npm run test` -> All tests should pass.

- [ ] Manual Test
- [x] Unit Test
- [ ] Integration / End-to-End Test

**Test Configuration**:

Not manually or integration tested because changes were only made to comments, tests, and documentation.

# Checklist:

- [ ] ~~My code follows the style guidelines of this project~~
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas that are not self-documenting
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings 
- [x] My changes have no unnecessary logging
- [x] I have added tests that prove my fix is effective or that my feature works, for sufficiently complex features
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Sensitive info like tokens, secrets, and passwords have been removed before submitting

Modified from this article:
Phillip Johnston, “A GitHub Pull Request Template for Your Projects - Embedded Artistry,” Embedded Artistry, Aug. 04, 2017. https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/ (accessed Jul. 22, 2021).

### CODE REVIEW

**Comment by parseccentric** [comment]
- [ ] Run unit tests

**Comment by parseccentric** [comment]
```
  Session
    √ should create one singular, correct sessions object
    √ should append a valid client to an empty session
    √ should append a duplicate client to a session
    √ should reduce two duplicate clients to one client
    √ should return true if it found a socket
    √ should return false if it couldn't find a socket
    √ should be able to remove a socket
    √ should return all session sockets for a given client ID
    √ should exclude a socket when requesting session sockets

  Sync Server: Clients and Sockets
    √ should return an error when appending a valid client to a null session
    √ should be able to bump one existing socket
    √ should be able to bump two existing sockets

  Sync Server: Integration
    √ should create a correct session object when a client joins
    √ should create a correct clients array
    √ should create a correct sockets object
    √ should perform a bump properly

  Sync Server: Sessions
    √ should have 0 sessions on startup
    √ should create one singular sessions object
    √ should return failure on getting a nonexistent session
    √ should return success for getting an existing session


  20 passing (44ms)
```

**Comment by parseccentric** [comment]
Re-ran the test just now with the same result. @ho-yi-shiuan can you take a look and merge it if it looks good? Thanks!

**Review by ho-yi-shiuan — APPROVED** [review]
Everything looks great!

**Comment by parseccentric** [comment]
Thank you!

**Pull request merged**
